# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("students", "Students"),
                            ("teachers", "Teachers"),
                            ("classes", "Classes"),
                            ("attendance", "Attendance"),
                            ("finance", "Finance"),
                            ("grades", "Grades"),
                        ],
                        max_length=20,
                        verbose_name="Statistic Type",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "period",
                    models.CharField(
                        default="daily",
                        help_text="daily, weekly, monthly, yearly",
                        max_length=20,
                        verbose_name="Period",
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("active_count", models.PositiveIntegerField(default=0)),
                (
                    "change_from_previous",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Change from Previous Period",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Details"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_stats",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Statistic",
                "verbose_name_plural": "Dashboard Statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SchoolActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "object_type",
                    models.CharField(max_length=100, verbose_name="Object Type"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="Object ID"),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Object Representation"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Old and new values of changed fields",
                        verbose_name="Changes",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
