# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolactivitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardstat",
            index=models.Index(
                fields=["school", "stat_type", "date"],
                name="analytics_d_school__9f9a03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardstat",
            index=models.Index(
                fields=["date", "period"], name="analytics_d_date_414060_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardstat",
            unique_together={("school", "stat_type", "date", "period")},
        ),
        migrations.AddIndex(
            model_name="schoolactivitylog",
            index=models.Index(
                fields=["school", "created_at"], name="analytics_s_school__f113c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolactivitylog",
            index=models.Index(
                fields=["user", "created_at"], name="analytics_s_user_id_fa2ad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolactivitylog",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="analytics_s_object__4ec0c1_idx",
            ),
        ),
    ]
