# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="Academic Year"),
                ),
                ("term", models.CharField(max_length=50, verbose_name="Term/Semester")),
                ("total_courses", models.PositiveSmallIntegerField(default=0)),
                ("total_credits", models.PositiveSmallIntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Average Score",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="GPA",
                    ),
                ),
                (
                    "rank_in_class",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Rank in Class"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "teacher_comments",
                    models.TextField(blank=True, verbose_name="Teacher Comments"),
                ),
                (
                    "principal_comments",
                    models.TextField(blank=True, verbose_name="Principal Comments"),
                ),
            ],
            options={
                "verbose_name": "Report Card",
                "verbose_name_plural": "Report Cards",
                "ordering": ["-academic_year", "term"],
            },
        ),
        migrations.CreateModel(
            name="CourseGradeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="Academic Year"),
                ),
                ("term", models.CharField(max_length=50, verbose_name="Term")),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "highest_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "lowest_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("passing_count", models.PositiveIntegerField(default=0)),
                ("failing_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_summaries",
                        to="classes.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_summaries",
                        to="classes.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grade_summaries",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Grade Summary",
                "verbose_name_plural": "Course Grade Summaries",
                "ordering": ["-academic_year", "term"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm"),
                            ("final", "Final Exam"),
                            ("project", "Project"),
                            ("homework", "Homework"),
                            ("participation", "Participation"),
                            ("other", "Other"),
                        ],
                        default="quiz",
                        max_length=20,
                        verbose_name="Exam Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Chapter 3 Quiz, First Midterm",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Score",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximum Score",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentage",
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="Exam Date")),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="Academic Year"),
                ),
                ("term", models.CharField(max_length=50, verbose_name="Term/Semester")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "class_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="classes.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="classes.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "ordering": ["-exam_date"],
            },
        ),
    ]
