# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grades", "0001_initial"),
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recorded By",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursegradesummary",
            unique_together={("class_record", "course", "academic_year", "term")},
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "course"], name="grades_grad_student_995530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["class_record", "exam_date"],
                name="grades_grad_class_r_172e27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "academic_year", "term"],
                name="grades_grad_student_d6f9c6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student", "academic_year", "term")},
        ),
    ]
