# Generated by Django 5.0.14 on 2026-05-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbsenceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consecutive_absences",
                    models.PositiveSmallIntegerField(
                        verbose_name="Consecutive Absences"
                    ),
                ),
                (
                    "total_absences_month",
                    models.PositiveSmallIntegerField(
                        verbose_name="Total Absences This Month"
                    ),
                ),
                ("alert_date", models.DateField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Absence Alert",
                "verbose_name_plural": "Absence Alerts",
                "ordering": ["-alert_date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                            ("sick", "Sick"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Arrival Time"
                    ),
                ),
                (
                    "minutes_late",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Minutes Late"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "sms_sent",
                    models.BooleanField(default=False, verbose_name="SMS Sent"),
                ),
                (
                    "sms_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="SMS Sent At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "student__student_code"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "total_students",
                    models.PositiveIntegerField(verbose_name="Total Students"),
                ),
                ("total_days", models.PositiveIntegerField(verbose_name="Total Days")),
                ("present_count", models.PositiveIntegerField(default=0)),
                ("absent_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("excused_count", models.PositiveIntegerField(default=0)),
                ("sick_count", models.PositiveIntegerField(default=0)),
                (
                    "attendance_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Attendance Rate %"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attendance Statistics",
                "verbose_name_plural": "Attendance Statistics",
                "ordering": ["-end_date"],
            },
        ),
    ]
