# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique ID for this teacher within the school",
                        max_length=50,
                        verbose_name="Employee ID",
                    ),
                ),
                (
                    "qualifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of degrees and certifications",
                        verbose_name="Qualifications",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Mathematics, Physics, English",
                        max_length=255,
                        verbose_name="Specialization",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="Hire Date"),
                ),
                (
                    "salary_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Base Salary (Toman)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "max_classes_per_day",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="Max Classes Per Day"
                    ),
                ),
                (
                    "working_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Schedule preferences and constraints",
                        verbose_name="Working Hours",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="Academic Year"),
                ),
                (
                    "is_primary_teacher",
                    models.BooleanField(
                        default=False,
                        help_text="Primary teacher is the homeroom/main teacher for this class",
                        verbose_name="Is Primary Teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Assignment",
                "verbose_name_plural": "Teacher Assignments",
            },
        ),
    ]
