# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0002_initial"),
        ("schools", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Account",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="classes.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="classes.course",
                verbose_name="Course",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="teachers.teacher",
                verbose_name="Teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["school", "employee_id"], name="teachers_te_school__33330d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["school", "status"], name="teachers_te_school__65785e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["specialization"], name="teachers_te_special_40f7e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacher",
            unique_together={("school", "employee_id")},
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(
                fields=["teacher", "academic_year"],
                name="teachers_te_teacher_8be4a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(
                fields=["class_assigned", "course"],
                name="teachers_te_class_a_e56756_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together={("teacher", "class_assigned", "course", "academic_year")},
        ),
    ]
