# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="School Name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used for subdomain and URL identification",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="schools/logos/%Y/%m/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code (e.g., #3B82F6)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Primary Color",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#10B981",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hex color code",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Secondary Color",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "current_academic_year",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 1403-1404",
                        max_length=20,
                        verbose_name="Current Academic Year",
                    ),
                ),
                (
                    "grading_system",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage (0-100)"),
                            ("gpa_4", "GPA 4.0"),
                            ("gpa_5", "GPA 5.0"),
                            ("custom", "Custom"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="Grading System",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom school settings and configurations",
                        verbose_name="Settings",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "subscription_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Subscription Expires At"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Subscription Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="schools_sch_slug_efcc78_idx"
                    ),
                    models.Index(
                        fields=["plan", "is_active"], name="schools_sch_plan_df0387_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Year Name")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Is Current"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Term Name")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Is Current"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="schools.academicyear",
                        verbose_name="Academic Year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Term",
                "verbose_name_plural": "Terms",
                "ordering": ["academic_year", "start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["school", "is_current"], name="schools_aca_school__0747e2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("school", "name")},
        ),
    ]
