# Generated by Django 5.0.14 on 2026-05-28 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_initial"),
        ("schools", "0001_initial"),
        ("teachers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("elementary", "Elementary (Grades 1-6)"),
                    ("middle", "Middle School (Grades 7-9)"),
                    ("high_school", "High School (Grades 10-12)"),
                ],
                default="elementary",
                max_length=20,
                verbose_name="Education Level",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="max_class_capacity",
            field=models.PositiveSmallIntegerField(
                default=30, verbose_name="Max Class Capacity"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="period_duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=45,
                help_text="Duration of each period in minutes",
                verbose_name="Period Duration (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="periods_per_day",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Number of class periods per day",
                verbose_name="Periods Per Day",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="school_start_time",
            field=models.TimeField(default="08:00", verbose_name="School Start Time"),
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(
                        help_text="Period number (1, 2, 3, ...)",
                        verbose_name="Period Number",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "ordering": ["school", "period_number"],
                "unique_together": {("school", "period_number")},
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("1", "Grade 1"),
                            ("2", "Grade 2"),
                            ("3", "Grade 3"),
                            ("4", "Grade 4"),
                            ("5", "Grade 5"),
                            ("6", "Grade 6"),
                            ("7", "Grade 7"),
                            ("8", "Grade 8"),
                            ("9", "Grade 9"),
                            ("10", "Grade 10"),
                            ("11", "Grade 11"),
                            ("12", "Grade 12"),
                        ],
                        max_length=2,
                        verbose_name="Grade Level",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("humanities", "Humanities"),
                        ],
                        help_text="Only for high school (grades 10-12)",
                        max_length=20,
                        null=True,
                        verbose_name="Branch",
                    ),
                ),
                (
                    "weekly_hours",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Number of hours per week for this course",
                        verbose_name="Weekly Hours",
                    ),
                ),
                (
                    "is_specialized",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a specialized course for the branch?",
                        verbose_name="Is Specialized",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_entries",
                        to="classes.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Entry",
                "verbose_name_plural": "Curriculum Entries",
                "ordering": ["grade_level", "branch", "course__name"],
                "unique_together": {("school", "grade_level", "branch", "course")},
            },
        ),
        migrations.CreateModel(
            name="GeneratedSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Saturday"),
                            (1, "Sunday"),
                            (2, "Monday"),
                            (3, "Tuesday"),
                            (4, "Wednesday"),
                            (5, "Thursday"),
                            (6, "Friday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="Academic Year"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_schedules",
                        to="classes.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_schedules",
                        to="classes.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_schedules",
                        to="teachers.teacher",
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_schedules",
                        to="schools.period",
                        verbose_name="Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Schedule",
                "verbose_name_plural": "Generated Schedules",
                "ordering": ["class_assigned", "day_of_week", "period__period_number"],
                "indexes": [
                    models.Index(
                        fields=["class_assigned", "academic_year"],
                        name="schools_gen_class_a_4b1c27_idx",
                    ),
                    models.Index(
                        fields=["teacher", "day_of_week", "period"],
                        name="schools_gen_teacher_c79f1f_idx",
                    ),
                    models.Index(
                        fields=["academic_year", "is_active"],
                        name="schools_gen_academi_c8d136_idx",
                    ),
                ],
                "unique_together": {
                    ("class_assigned", "day_of_week", "period", "academic_year")
                },
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Saturday"),
                            (1, "Sunday"),
                            (2, "Monday"),
                            (3, "Tuesday"),
                            (4, "Wednesday"),
                            (5, "Thursday"),
                            (6, "Friday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "periods",
                    models.JSONField(
                        default=list,
                        help_text="List of period numbers teacher is available (e.g., [1, 2, 3])",
                        verbose_name="Available Periods",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="teachers.teacher",
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Availability",
                "verbose_name_plural": "Teacher Availabilities",
                "ordering": ["teacher", "day_of_week"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "day_of_week"],
                        name="schools_tea_teacher_d8f25a_idx",
                    )
                ],
                "unique_together": {("teacher", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="TeacherSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "grade_levels",
                    models.JSONField(
                        default=list,
                        help_text='List of grade levels teacher can teach this course (e.g., ["10", "11", "12"])',
                        verbose_name="Grade Levels",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_specializations",
                        to="classes.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="teachers.teacher",
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Specialization",
                "verbose_name_plural": "Teacher Specializations",
                "indexes": [
                    models.Index(
                        fields=["teacher", "course"],
                        name="schools_tea_teacher_143f8c_idx",
                    )
                ],
                "unique_together": {("teacher", "course")},
            },
        ),
    ]
