# Generated by Django 5.0.14 on 2026-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_add_scheduling_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Whether this year is shown to school admins for selection.",
                verbose_name="Show in Managers Panel",
            ),
        ),
    ]
