# Generated by Django 5.0.14 on 2026-06-13 10:08

from django.db import migrations, models


def clear_empty_national_ids(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(national_id='').update(national_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="National ID",
            ),
        ),
        migrations.RunPython(clear_empty_national_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="National ID",
            ),
        ),
    ]
