# Generated by Django 5.0.14 on 2026-05-31 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0002_initial"),
        ("schools", "0002_add_scheduling_models"),
        ("students", "0002_initial"),
        ("teachers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Exam Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("1", "Grade 1"),
                            ("2", "Grade 2"),
                            ("3", "Grade 3"),
                            ("4", "Grade 4"),
                            ("5", "Grade 5"),
                            ("6", "Grade 6"),
                            ("7", "Grade 7"),
                            ("8", "Grade 8"),
                            ("9", "Grade 9"),
                            ("10", "Grade 10"),
                            ("11", "Grade 11"),
                            ("12", "Grade 12"),
                        ],
                        max_length=2,
                        verbose_name="Grade Level",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("humanities", "Humanities"),
                            ("", "No Branch (Elementary/Middle)"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Branch",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm"),
                            ("final", "Final Exam"),
                            ("practice", "Practice"),
                        ],
                        default="quiz",
                        max_length=20,
                        verbose_name="Exam Type",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(verbose_name="Scheduled Start Time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="If not set, exam ends based on duration",
                        null=True,
                        verbose_name="Scheduled End Time",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Maximum time allowed for the exam",
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        {\n            "shuffle_questions": true,\n            "shuffle_options": true,\n            "show_result_immediately": false,\n            "max_attempts": 1,\n            "passing_percentage": 50,\n            "allow_review_after_finish": true,\n            "prevent_copy_paste": true,\n            "tab_switch_limit": 3,\n            "tab_switch_action": "warn",\n            "fullscreen_required": false,\n            "webcam_required": false\n        }\n        ',
                        verbose_name="Exam Settings",
                    ),
                ),
                (
                    "total_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Total Points",
                    ),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Question Count"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="classes.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "created_by_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_exams",
                        to="teachers.teacher",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("1", "Grade 1"),
                            ("2", "Grade 2"),
                            ("3", "Grade 3"),
                            ("4", "Grade 4"),
                            ("5", "Grade 5"),
                            ("6", "Grade 6"),
                            ("7", "Grade 7"),
                            ("8", "Grade 8"),
                            ("9", "Grade 9"),
                            ("10", "Grade 10"),
                            ("11", "Grade 11"),
                            ("12", "Grade 12"),
                        ],
                        db_index=True,
                        max_length=2,
                        verbose_name="Grade Level",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science"),
                            ("humanities", "Humanities"),
                            ("", "No Branch (Elementary/Middle)"),
                        ],
                        db_index=True,
                        help_text="Only for high school (grades 10-12)",
                        max_length=20,
                        null=True,
                        verbose_name="Branch",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short identifier for this question",
                        max_length=255,
                        verbose_name="Question Title",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay/Descriptive"),
                            ("fill_blank", "Fill in the Blank"),
                            ("matching", "Matching"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="Question Type",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question Text")),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Question options and configuration",
                        verbose_name="Options",
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Correct answer for auto-grading",
                        verbose_name="Correct Answer",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Points",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "media_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of attached files [{"type": "image/pdf/audio", "url": "..."}]',
                        verbose_name="Media Files",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Is Approved"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Visible to other teachers in the school",
                        verbose_name="Is Public",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times this question has been used in exams",
                        verbose_name="Usage Count",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="classes.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "created_by_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_questions",
                        to="teachers.teacher",
                        verbose_name="Created By",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Bank",
                "verbose_name_plural": "Question Bank",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "points_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="If set, overrides the question default points",
                        max_digits=5,
                        null=True,
                        verbose_name="Points Override",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_questions",
                        to="exams.exam",
                        verbose_name="Exam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_usages",
                        to="exams.questionbank",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Question",
                "verbose_name_plural": "Exam Questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Only PDF files allowed",
                        upload_to="questions/files/%Y/%m/",
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="File Name"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="File Size (bytes)"),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Page Count"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("linked", "Linked to Question"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="exams.questionbank",
                        verbose_name="Question",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="teachers.teacher",
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question File",
                "verbose_name_plural": "Question Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("timeout", "Time Out"),
                            ("cheating_detected", "Cheating Detected"),
                        ],
                        default="not_started",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Attempt Number"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "time_spent_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Time Spent (minutes)"
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Total Score",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentage",
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(blank=True, null=True, verbose_name="Passed"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "tab_switch_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tab Switch Count"
                    ),
                ),
                (
                    "fullscreen_exit_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fullscreen Exit Count"
                    ),
                ),
                (
                    "answers_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of all answers at submission time",
                        verbose_name="Answers Snapshot",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_exams",
                        to="exams.exam",
                        verbose_name="Exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_participations",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Exam",
                "verbose_name_plural": "Student Exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(blank=True, verbose_name="Answer Text"),
                ),
                (
                    "answer_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured answer data for complex question types",
                        verbose_name="Answer JSON",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score",
                    ),
                ),
                (
                    "is_auto_graded",
                    models.BooleanField(default=False, verbose_name="Is Auto Graded"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Graded At"
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Feedback")),
                (
                    "ai_grade_suggested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="AI Suggested Grade",
                    ),
                ),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="AI Confidence",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Graded By",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="exams.questionbank",
                        verbose_name="Question",
                    ),
                ),
                (
                    "student_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.studentexam",
                        verbose_name="Student Exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Answer",
                "verbose_name_plural": "Student Answers",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["school", "status"], name="exams_exam_school__092099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["created_by_teacher", "status"],
                name="exams_exam_created_df67e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["grade_level", "branch", "course"],
                name="exams_exam_grade_l_32b6d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["scheduled_at", "status"], name="exams_exam_schedul_5f23f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["school", "grade_level", "branch", "course"],
                name="exams_quest_school__1dab32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["school", "status", "is_approved"],
                name="exams_quest_school__288778_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["created_by_teacher", "status"],
                name="exams_quest_created_c39e44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["school", "is_public", "status"],
                name="exams_quest_school__d6f1d6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examquestion",
            unique_together={("exam", "question")},
        ),
        migrations.AddIndex(
            model_name="studentexam",
            index=models.Index(
                fields=["student", "exam"], name="exams_stude_student_2fba81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentexam",
            index=models.Index(
                fields=["exam", "status"], name="exams_stude_exam_id_e8ebea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentexam",
            index=models.Index(
                fields=["student", "status"], name="exams_stude_student_c3073f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentexam",
            unique_together={("student", "exam", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together={("student_exam", "question")},
        ),
    ]
