# Generated by Django 5.0.14 on 2026-05-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("schools", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classes",
                to="teachers.teacher",
                verbose_name="Homeroom Teacher",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="classes.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_periods",
                to="teachers.teacher",
                verbose_name="Teacher",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="schools.school",
                verbose_name="School",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_periods",
                to="classes.course",
                verbose_name="Course",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["school", "grade_level"], name="classes_cla_school__9cd6a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["school", "is_active"], name="classes_cla_school__c99f2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["homeroom_teacher"], name="classes_cla_homeroo_6939fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("school", "name", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["school", "code"], name="classes_cou_school__e3daaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["school", "category"], name="classes_cou_school__09b919_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["school", "is_active"], name="classes_cou_school__2c8dee_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("school", "code")},
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["class_assigned", "day_of_week"],
                name="classes_cla_class_a_d2474b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["teacher", "day_of_week"], name="classes_cla_teacher_d80044_idx"
            ),
        ),
    ]
