# Generated by Django 5.0.14 on 2026-05-31 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_initial"),
        ("schools", "0002_add_scheduling_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="course",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="course",
            name="is_global",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this course is available to all schools",
                verbose_name="Is Global",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_global", "is_active"], name="classes_cou_is_glob_1832d7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                condition=models.Q(("school__isnull", True)),
                fields=("code",),
                name="unique_global_course_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("school", "code"), name="unique_school_course_code"
            ),
        ),
    ]
