# Generated by Django 5.0.14 on 2026-05-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "student_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for this student within the school",
                        max_length=50,
                        verbose_name="Student Code",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Enrollment Date"
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        help_text="e.g., 10, 11, 12 for high school",
                        max_length=20,
                        verbose_name="Grade Level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("graduated", "Graduated"),
                            ("suspended", "Suspended"),
                            ("transferred", "Transferred"),
                            ("dropped", "Dropped"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Guardian Name"
                    ),
                ),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Guardian Phone"
                    ),
                ),
                (
                    "guardian_relationship",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Father, Mother, Uncle",
                        max_length=50,
                        verbose_name="Guardian Relationship",
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Previous School"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True, verbose_name="Allergies / Medical Conditions"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("transcript", "Transcript"),
                            ("certificate", "Certificate"),
                            ("medical", "Medical Record"),
                            ("photo", "Photo"),
                            ("id_card", "ID Card"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="students/documents/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Student Document",
                "verbose_name_plural": "Student Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
