# Generated by Django 5.0.14 on 2026-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_studentenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="father_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Father Phone"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Mother Phone"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_completed",
            field=models.BooleanField(default=False, verbose_name="Profile Completed"),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_level",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g., 10, 11, 12 for high school",
                max_length=20,
                verbose_name="Grade Level",
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("transcript", "Transcript"),
                    ("certificate", "Certificate"),
                    ("medical", "Medical Record"),
                    ("photo", "Photo"),
                    ("id_card", "ID Card"),
                    ("registration", "Registration"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Document Type",
            ),
        ),
    ]
